### ISSUE TITLE
I can`t find the footprint of F1C100s

### ISSUE THREAD

**Issue by chengxus** [thirtythreeforty/3340_kicad#1]
Excuse me ，I can't find F1C100s in your KiCAD parts library,
Can you tall me what is it's name,or you may be submit it,I want to study it, Thank you.

**Comment by thirtythreeforty** [comment]
Welp that's because I'm stupid... Just checked and I forgot to add it.  Give me 20 minutes and I'll have it pushed.  Sorry for the misdirection.

**Comment by thirtythreeforty** [comment]
Fixed in `430e003`.
