### ISSUE TITLE
Add some license?

### ISSUE THREAD

**Issue by Icenowy** [thirtythreeforty/3340_kicad#2]
Could there be some license file that we can reuse these symbols/footprints in open source projects?

**Comment by thirtythreeforty** [comment]
That's a good question. Yes, definitely needs a formal license... I am normally a license nerd, but in this case I don't have a strong opinion.

What do you think about copying the [KiCAD library license](https://kicad-pcb.org/libraries/license/)?

> The KiCad libraries are licensed under the Creative Commons CC-BY-SA 4.0 License, with the following exception:
> > To the extent that the creation of electronic designs that use 'Licensed Material' can be considered to be 'Adapted Material', then the copyright holder waives article 3 of the license with respect to these designs and any generated files which use data provided as part of the 'Licensed Material'.

**Comment by Icenowy** [comment]
I think it's okay. Thanks.
